export const CART_MAIN_GET = 'CART_MAIN_GET';
export const CART_SETTLEMENT_MAIN_GET = 'CART_SETTLEMENT_MAIN_GET';
export const CART_ADDRESS_MAIN_GET = 'CART_ADDRESS_MAIN_GET';
export const CART_ADDRESS_DEL_MAIN_GET = 'CART_ADDRESS_DEL_MAIN_GET';

