export const CART_MAIN_GET = 'CART_MAIN_GET';
export const CART_COUNT_CHANGE_POST = 'CART_COUNT_CHANGE_POST';		// 加入购物车
export const CART_COUNT_DELETE_POST = 'CART_COUNT_DELETE_POST';   	// 购物车删除
export const CART_SELECT_CHANGE = 'CART_SELECT_CHANGE';  			// 购物车多选
export const CART_SETTLEMENT_MAIN_GET = 'CART_SETTLEMENT_MAIN_GET';
export const CART_ADDRESS_MAIN_GET = 'CART_ADDRESS_MAIN_GET';
export const CART_ADDRESS_DEL_MAIN_GET = 'CART_ADDRESS_DEL_MAIN_GET';

