export const USER_MAIN_GET = 'USER_MAIN_GET';
export const USER_COUPON_GET = 'USER_COUPON_GET';
export const USER_BALANCE_MAIN_GET = 'USER_BALANCE_MAIN_GET';
export const USER_INTEGRAL_MAIN_GET = 'USER_INTEGRAL_MAIN_GET';
export const USER_BALANCE_RECHARGE_POST = 'USER_BALANCE_RECHARGE_POST';  // 余额充值

